# Generated by Django 3.1.14 on 2022-12-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20221209_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='Contact',
        ),
    ]
